apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{- include "cdp-private-hdfs-sp.labels" . | nindent 4 }}
  name: {{ template "cdp-private-hdfs-sp.fullname" . }}-config
data:
  application.yml: |
  {{- if .Values.configOverride -}}
  {{- .Values.configOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/application.yml" | nindent 4 }}
  {{ end }}
  krb5.conf: |
  {{- if .Values.krb5Override -}}
  {{- .Values.krb5Override | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/krb5.conf" | nindent 4 }}
  {{ end }}
