apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: "cdp-private-hdfs"
          valueMap:
            cdp-private-hdfs-keytab: base64-encoded-content
            LDAP_BIND_PASSWORD: pwd
            RANGER_PASSWORD: pwd
            cdp-private-hdfs-custom-ca: content
