spring:
  application:
    name: cdp-private-hdfs-specific-provisioner

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /docs

logging:
  level:
    org.apache.ranger.RangerClient: DEBUG
    sun.net.www.protocol.http.HttpURLConnection: DEBUG
    org.apache.hc.client5.http: DEBUG

kerberos:
  keytabLocation: /opt/docker/etc/security/cdp/private/hdfs/keytab
  principal: user

hdfs:
  baseUrl: http://webhdfs-host:50070
  timeout: 30000

ranger:
  baseUrl: http://ranger-host
  timeout: 30000
  username: admin
  password: ${RANGER_PASSWORD}
  hdfsServiceName: cm_hdfs
  ownerTechnicalUser: admin

mapping:
  ldap:
    url: ldap://host:port
    useTls: false
    timeout: 30000
    bindUsername: user
    bindPassword: ${LDAP_BIND_PASSWORD}
    searchBaseDN: DC=agilelab,DC=it
    userSearchFilter: (mail={mail})
    groupSearchFilter: (&(objectClass=groupOfNames)(cn={group}))
    userAttributeName: cn
    groupAttributeName: cn
